FROM --platform=$BUILDPLATFORM alpine
ARG LINK
ARG TARGETPLATFORM
COPY ./setup.sh /setup.sh
RUN /setup.sh

FROM node:lts-alpine
COPY --from=0 /koishi /koishi
RUN apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont font-noto-cjk && \
    adduser -D koishi && \
    chown -R koishi /koishi
USER koishi
WORKDIR /koishi
ENTRYPOINT [ "yarn", "start" ]
